# Generated by Django 4.0.2 on 2022-03-05 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='titile',
            new_name='title',
        ),
    ]
